[[redirects]]
  from = "/slides/web-perf-time-to-pizza"
  to = "https://speakerdeck.com/iankduffy/web-perf-time-to-pizza"
  status = 302
  force = true

[[redirects]]
  from = "/slides/web-perf-time-to-pizza/"
  to = "https://speakerdeck.com/iankduffy/web-perf-time-to-pizza"
  status = 302
  force = true
